### ISSUE TITLE
Async I/O for NetLink socket

### ISSUE THREAD

**Issue by TjeuKayim** [nbdd0121/nfq-rs#5]
This fork of `nfq-rs` implements async I/O for the NetLink socket with Tokio https://github.com/TjeuKayim/nfq-rs/tree/async. It is running fine, but I didn't stress test it yet. My work is based on https://github.com/little-dude/netlink/tree/master/netlink-sys/ (MIT license).

What would be the best approach to merge these changes into this project? The blocking and async implementations could be in different modules, depending on a module with shared code. A feature flag named `tokio` swaps the module for an async variant. I would like to hear your opinion.

**Comment by nbdd0121** [comment]
> A feature flag named `tokio` swaps the module for an async variant.

This wouldn't work, because features are merged, so if we have one crate depending on sync variant and another on async variant then they'll break.

> The blocking and async implementations could be in different modules, depending on a module with shared code.

This sounds like a better approach.

One thing to consider about is how to make sure the async variant can work with both `async-std` and `tokio`.

**Comment by nbdd0121** [comment]
> One thing to consider about is how to make sure the async variant can work with both `async-std` and `tokio`.

One approach might be using [`smol::Async`](https://docs.rs/smol/0.1.8/smol/struct.Async.html).

**Comment by TjeuKayim** [comment]
`smol` seems promising

**Comment by rustn00b** [comment]
I needed an `async-std` variant of `nfq` and after failing to find something that fit my needs (uninspired googling?), I then tried to put something together myself.  This variant introduces a dependency on `async-io` if the `async` feature is selected. It is then possible to use constructs like the following:

```rust
#[async_std::main]
async fn main() -> Result<()> {
   let mut queue = Queue::open()?;
   queue.bind(0)?;
   let mut queue = AsyncQueue::new(queue)?;
   loop {
       let mut msg = queue.recv().await?;
       msg.set_verdict(Verdict::Accept);
       println!("{:#?}", msg);
       queue.verdict(msg).await?;    
   }
}
```

Wrt my use case it has been working quite nicely. It can be found here: https://github.com/rustn00b/nfq-rs.
I'm quite new to Rust (async or otherwise) so I would really welcome feedback that helps me gain insights into how to do things right, or even just better.

**Comment by nbdd0121** [comment]
I think to work nicely with `async-io` simply implement `AsRawFd` for `Queue` and add a private `try_verdict` method that borrows the message instead of consuming the message.

Then one can easily implement async recv with `self.read_with(|io| io.recv())` and async verdict with `self.write_with(|io| io.try_verdict(&msg))`.

**Comment by rustn00b** [comment]
I tried the suggestion and it makes the async variant more concise. However using `read_with/write_with` triggers a compile error in client code that uses the library if it happens to use the queue inside a `task::spawn` (this was not the case with my basic initial implementation). For instance:
```rust
...
    task::spawn(async move {
        let msg = queue.recv().await.unwrap();
        queue.verdict(msg).await.unwrap();    
    });
```
Triggers the following error:
```
error[E0277]: `*const i8` cannot be shared between threads safely
  --> async_rust_nfqueue/src/main.rs:32:5
   |
32 |     task::spawn(async move {
   |     ^^^^^^^^^^^ `*const i8` cannot be shared between threads safely
   |
   = help: within `Message`, the trait `Sync` is not implemented for `*const i8`
```
While I think I can see why a pointer may not be `Sync`, I didn't get why the compiler determines that `Message` is accessed by different threads/tasks. My admittedly limited understanding is that `Send` should be enough (and also happens to be available on `Message` :-)

**Comment by nbdd0121** [comment]
I think I understand what's the issue now. The thing that has to be `Sync` is actually `Queue`, which contains `VecDeque<Message>` so `Message` needs to be `Sync` for the queue to be `Sync`. I had a look and I think `Message` is indeed `Sync`, so what's lacking is just an impl.

**Comment by rustn00b** [comment]
Indeed, just adding the `Sync` impl for `Message` did the trick and my toy example works. However my current level of understanding of Rust (sadly) doesn't allow me to confidently claim that the change is in fact "safe".
I updated a branch in my local fork with the change. Thanks for your feedback and suggestions!

**Comment by clintfred** [comment]
@TjeuKayim Are you still maintaining your fork? I am interested in a tokio version of nfq-rs and would be open to collaborating with you. 

@rustn00b Have you thought more about bringing the tokio version in as a separate module, enabled by a feature flag?

**Comment by TjeuKayim** [comment]
> @TjeuKayim Are you still maintaining your fork? I am interested in a tokio version of nfq-rs and would be open to collaborating with you. 

No, my nfq fork is not maintained. I don't need it anymore.

**Comment by nbdd0121** [comment]
@clintfred I have added a `AsRawFd` implementation for `Queue`. Hopefully you should be able to use tokio's [AsyncFd](https://docs.rs/tokio/latest/tokio/io/unix/struct.AsyncFd.html) now?

**Comment by clintfred** [comment]
@nbdd0121 Thanks for your response and the `AsRawFd` impl.  I haven't had a chance to test it out, but sometime in the next few weeks I should be able to make time to dig in a little more. Do you want me to report back on this closed issue, or just open a new issue if/when I have issues?

**Comment by nbdd0121** [comment]
You can open a new issue.
